---
title: "Week 5B: Joint, Marginal, and Conditional Distributions"
subtitle: "*DSAN 5100: Probabilistic Modeling and Statistical Computing*<br>Section 01"
author: "Purna Gamage, Amineh Zadbood, and Jeff Jacobs"
date: 2025-09-23
date-format: full
lecnum: 7
bibliography: "../_DSAN5100.bib"
cache: false
categories:
  - "Class Sessions"
format:
  revealjs:
    footer: "DSAN 5100 W05B: Joint, Marginal, Conditional Distributions"
    output-file: slides.html
    df-print: kable
    code-fold: true
    html-math-method: mathjax
    scrollable: true
    slide-number: true
    number-sections: false
    tbl-cap-location: bottom
    link-external-icon: true
    link-external-newwindow: true
    theme: [default, "../dsan-globals/jjquarto.scss"]
    revealjs-plugins:
      - simplemenu
    simplemenu:
      flat: true
      barhtml:
        header: "<div class='menubar'><span style='position: absolute; left: 8; padding-left: 8px;'><a href='./index.html'>&larr; Return to Notes</a></span><ul class='menu'></ul></div>"
      scale: 0.5
    include-in-header:
      text: "<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css'><link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/gh/dreampulse/computer-modern-web-font@master/fonts.css'><link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH' crossorigin='anonymous'><script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz' crossorigin='anonymous'></script>"
  html:
    output-file: index.html
    df-print: kable
    warning: false
    link-external-icon: true
    link-external-newwindow: true
---

::: {.content-visible unless-format="revealjs"}

<center>
<a class="h2" href="slides.html" target="_blank">Open slides in new window &rarr;</a>
</center>

:::

# Frequency Tables $\leftrightarrow$ Probabilities {data-stack-name="Frequency vs. Probability"}

::: {.hidden}

```{r}
#| label: r-source-globals
source("../dsan-globals/_globals.r")
```

{{< include ../_globals-tex.qmd >}}

:::

## Frequency Tables {.fix-tex-headers .crunch-title .text-85 .crunch-quarto-layout-cell}

:::: {layout-ncol=2}

::: {#freq-table-text}

* What does Table 1 tell us **on its own** (before computing proportions in our heads) that is useful for probability?
* Answer: Not much!
* But, once we find the **overall total**, it tells us **a lot** (everything we need to know!)

:::

::: {#tbl-freq}

```{=html}
<table>
<caption>
    <span>&nbsp;</span>
</caption>
<thead>
  <tr>
    <th></th>
    <th><span data-qmd="$H = 0$"></span></th>
    <th><span data-qmd="$H = 1$"></span></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><span data-qmd="$G = 10$"></span></td>
    <td class='cb1a-bg'>10</td>
    <td class='cb1a-bg'>5</td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 11$"></span></td>
    <td class='cb1a-bg'>6</td>
    <td class='cb1a-bg'>4</td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 12$"></span>
    <td class='cb1a-bg'>7</td>
    <td class='cb1a-bg'>1</td>
  </tr>
</table>
```

A frequency table of HS students<br>($G$ = grade, $H$ = honors status)<br><span style='display: inline-flex; border: 1px solid black;'>*Tells us, e.g., 5 honors students in grade 10*</span>
:::

::::

::: {.notes}

[A frequency table where each **row** corresponds to a grade in a certain senior high school, each **column** corresponds to honor-student-status ($H=1$ represents honors, $H=0$ represents non-honors), and each **cell** contains the **number of students** in that grade with that honors-status]{.small-caption}

:::

## Why Do We Need The Total? {.text-95 .inline-90}

* **Q1**: Someone asks the **probability** that a randomly-selected student will be an **honor student** in **11th grade**.
* **Q2**: Someone asks what **proportion** of students are honors
* **Q3**: Someone asks what **%** of 12th grade are honors

***Q1**, for example, is asking us for $\Pr(G = 11, H = 1)$, a question we can answer if we know the **joint distribution** $f_{G,H}(g, h)$*

## Back to the Naïve Definition

Using our **naïve definition of probability**, we can compute this probability using the **frequencies** in the table as

$$
\Pr(G = 11, H = 1) = \frac{\#[G = 11, H = 1]}{\#\text{ Students Total}}
$$

Plugging in the values from @tbl-freq, we obtain the answer:

$$
\Pr(G = 11, H = 1) = \frac{4}{33} \approx 0.121
$$

## Frequency Table &rarr; Probability Table {.title-09}

* When we divide by **33**, we are **normalizing** the counts, producing probabilities (normalized counts)
* By normalizing **all cells** in the table, we convert our **frequency table** into a **probability table**

## Computing Overall Total by Column {.fix-tex-headers .title-09}

We could compute the total by summing **columns**, then summing over our individual column totals to get 33:

```{=html}
<table>
<thead>
  <tr>
    <th></th>
    <th><span data-qmd="$H = 0$"></span></th>
    <th><span data-qmd="$H = 1$"></span></th>
    <th>Total</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><span data-qmd="$G = 10$"></span></td>
    <td class='cb1a-bg'>10</td>
    <td class='cb1a-bg'>5</td>
    <td></td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 11$"></span></td>
    <td class='cb1a-bg'>6</td>
    <td class='cb1a-bg'>4</td>
    <td></td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 12$"></span>
    <td class='cb1a-bg'>7</td>
    <td class='cb1a-bg'>1</td>
    <td></td>
  </tr>
  <tr>
    <td><span data-qmd="**Total**"></span></td>
    <td class='cb2a-bg'>23</td>
    <td class='cb2a-bg'>10</td>
    <td class='cbga-bg'>33</td>
  </tr>
</table>
```

## Computing Overall Total by Row {.fix-tex-headers .title-09}

**Or**, we could compute the total by summing **rows**, then summing over our individual row totals to get 33:

```{=html}
<table>
<thead>
  <tr>
    <th></th>
    <th><span data-qmd="$H = 0$"></span></th>
    <th><span data-qmd="$H = 1$"></span></th>
    <th>Total</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><span data-qmd="$G = 10$"></span></td>
    <td class='cb1a-bg'>10</td>
    <td class='cb1a-bg'>5</td>
    <td class='cb2a-bg'>15</td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 11$"></span></td>
    <td class='cb1a-bg'>6</td>
    <td class='cb1a-bg'>4</td>
    <td class='cb2a-bg'>10</td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 12$"></span>
    <td class='cb1a-bg'>7</td>
    <td class='cb1a-bg'>1</td>
    <td class='cb2a-bg'>8</td>
    <td></td>
  </tr>
  <tr>
    <td><span data-qmd="**Total**"></span></td>
    <td></td>
    <td></td>
    <td class='cbga-bg'>33</td>
  </tr>
</table>
```

## Bringing Both Methods Together {.fix-tex-headers}

::: {#tbl-marginal-freq}

```{=html}
<table>
<caption><span></span></caption>
<thead>
  <tr>
    <th></th>
    <th><span data-qmd="$H = 0$"></span></th>
    <th><span data-qmd="$H = 1$"></span></th>
    <th>Total</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><span data-qmd="$G = 10$"></span></td>
    <td class='cb1a-bg'>10</td>
    <td class='cb1a-bg'>5</td>
    <td class='cb2a-bg'>15</td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 11$"></span></td>
    <td class='cb1a-bg'>6</td>
    <td class='cb1a-bg'>4</td>
    <td class='cb2a-bg'>10</td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 12$"></span>
    <td class='cb1a-bg'>7</td>
    <td class='cb1a-bg'>1</td>
    <td class='cb2a-bg'>8</td>
    <td></td>
  </tr>
  <tr>
    <td><span data-qmd="**Total**"></span></td>
    <td class='cb2a-bg'>23</td>
    <td class='cb2a-bg'>10</td>
    <td class='cbga-bg'>33</td>
  </tr>
</table>
```

The same frequency table as in @tbl-freq, but now with row and column totals representing **marginal frequencies**
:::

## Frequencies to Probabilities {.fix-tex-headers}

:::: {layout-ncol=2 layout-valign="center"}
::: {#prob-table-text}

Now let's use **overall total** (33) to convert **counts** into **probabilities**:

:::
::: {#tbl-marginal-prob}

```{=html}
<table>
  <caption><span></span></caption>
  <thead>
    <tr>
      <th></th>
      <th><span data-qmd="$H = 0$"></span></th>
      <th><span data-qmd="$H = 1$"></span></th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td><span data-qmd="$G = 10$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{10}{33}$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{5}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{15}{33}$"></span></td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 11$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{6}{33}$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{4}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{10}{33}$"></span></td>
  </tr>
  <tr>
    <td><span data-qmd="$G = 12$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{7}{33}$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{1}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{8}{33}$"></span></td>
  </tr>
  <tr>
    <td><span data-qmd="**Total**"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{23}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{10}{33}$"></span></td>
    <td class='cbga-bg'><span data-qmd="$\frac{33}{33}$"></span></td>
  </tr>
  </tbody>
</table>
```

Table from prev slide with all values **normalized** (divided by the total number of obs)
:::

::::

# Distributions in Discrete World {data-stack-name="Discrete World" .not-title-slide .title-12 .smaller .crunch-title .crunch-ul .crunch-img .crunch-math .math-80 .crunch-quarto-figure .highlight-col1}

{{< include ../_components/discrete-vs-continuous.qmd >}}

## One Table, Three Distributions! {.crunch-title .crunch-ul .inline-90 .text-85 .crunch-quarto-layout-cells}

Now that we have **normalized counts**, different pieces of this table give different **probability distributions**:

:::: {layout="[56,44]" layout-valign="center"}
::: {#three-dist-text}

[**Joint Distribution**]{.cb1a-bg} $f_{G,H}(g, h)$: Look at **value** in row $g$, col $h$<br>

[**Two Marginal Distributions**]{.cb2a-bg}

<i class='bi bi-1-circle pe-1'></i>$f_G(g)$: Look at **total** for **row $g$**

<i class='bi bi-2-circle pe-1'></i>$f_H(h)$: Look at **total** for **column $h$**

:::
::: {#three-dist-table}

```{=html}
<table>
  <thead>
    <tr>
      <th></th>
      <th class='small-tex-th'><span data-qmd="$H = 0$"></span></th>
      <th class='small-tex-th'><span data-qmd="$H = 1$"></span></th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td class='small-tex-td'><span data-qmd="$G = 10$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{10}{33}$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{5}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{15}{33}$"></span></td>
  </tr>
  <tr>
    <td class='small-tex-td'><span data-qmd="$G = 11$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{6}{33}$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{4}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{10}{33}$"></span></td>
  </tr>
  <tr>
    <td class='small-tex-td'><span data-qmd="$G = 12$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{7}{33}$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{1}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{8}{33}$"></span></td>
  </tr>
  <tr>
    <td><span data-qmd="**Total**"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{23}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{10}{33}$"></span></td>
    <td class='cbga-bg'><span data-qmd="$\frac{33}{33}$"></span></td>
  </tr>
  </tbody>
</table>
```

:::
::::

## Summary: Joint &rarr; Marginal {.smaller .crunch-title .inline-95 .crunch-ul .text-65}

* Note how **[marginal distributions]{.cb2a-bg}** were obtained by **summing** the **[joint distribution]{.cb1a-bg}** over a particular **dimension**:
* Summing each **column** ($H = 0$ and $H = 1$) produced **[marginal distribution]{.cb2a-bg} of $H$**:

::: {layout-ncol=2}

```{=html}
<table>
<thead></thead>
<tbody>
  <tr>
    <td></td>
    <td class='cb1a-bg'><span data-qmd="$\Pr(H = 0, G = 10)$"></span></td>
  </tr>
  <tr>
    <td>+</td>
    <td class='cb1a-bg'><span data-qmd="$\Pr(H = 0, G = 11)$"></span></td>
  </tr>
  <tr>
    <td>+</td>
    <td class='cb1a-bg'><span data-qmd="$\Pr(H = 0, G = 12)$"></span></td>
  </tr>
  <tr>
    <td>=</td>
    <td class='cb2a-bg'><span data-qmd="$\Pr(H = 0)$"></span></td>
  </tr>
</tbody>
</table>
```

```{=html}
<table>
<thead></thead>
<tbody>
  <tr>
    <td></td>
    <td class='cb1a-bg'><span data-qmd="$\Pr(H = 1, G = 10)$"></span></td>
  </tr>
  <tr>
    <td>+</td>
    <td class='cb1a-bg'><span data-qmd="$\Pr(H = 1, G = 11)$"></span></td>
  </tr>
  <tr>
    <td>+</td>
    <td class='cb1a-bg'><span data-qmd="$\Pr(H = 1, G = 12)$"></span></td>
  </tr>
  <tr>
    <td>=</td>
    <td class='cb2a-bg'><span data-qmd="$\Pr(H = 1)$"></span></td>
  </tr>
</tbody>
</table>
```
:::

* Summing each **row** ($G = 10$, $G = 11$, $G = 12$) produced **[marginal distribution]{.cb2a-bg} of $G$**:

```{=html}
<table>
<thead></thead>
<tbody>
  <tr>
    <td class='cb1a-bg'><span data-qmd="$\Pr(G = 10, H = 0)$"></span></td>
    <td>+</td>
    <td class='cb1a-bg'><span data-qmd="$\Pr(G = 10, H = 1)$"></span></td>
    <td>=</td>
    <td class='cb2a-bg'><span data-qmd="$\Pr(G = 10)$"></span></td>
  </tr>
  <tr>
    <td class='cb1a-bg'><span data-qmd="$\Pr(G = 11, H = 0)$"></span></td>
    <td>+</td>
    <td class='cb1a-bg'><span data-qmd="$\Pr(G = 11, H = 1)$"></span></td>
    <td>=</td>
    <td class='cb2a-bg'><span data-qmd="$\Pr(G = 11)$"></span></td>
  </tr>
  <tr>
    <td class='cb1a-bg'><span data-qmd="$\Pr(G = 12, H = 0)$"></span></td>
    <td>+</td>
    <td class='cb1a-bg'><span data-qmd="$\Pr(G = 12, H = 1)$"></span></td>
    <td>=</td>
    <td class='cb2a-bg'><span data-qmd="$\Pr(G = 12)$"></span></td>
  </tr>
</tbody>
</table>
```

## What's Missing? Conditional Distributions {.smaller .title-12 .crunch-title}

* [**Conditional distribution**]{.cb3a-bg} does not represent a **sum** but a **slice**: we consider e.g. **one particular row** or **one particular column** of the table.
* **🚨Warning🚨!** unlike in **joint** and **marginal** cases, when computing **conditional** distributions we have to **renormalize**, since we are "entering world" where we only consider **subsets** of the table where condition is met!
* Recall slide about how **all distributions are conditional distributions**:

:::: {.columns}
::: {.column width="33%"}

<center>
[$\Pr(G = 10, H = 1)$]{.cb1a-bg}
</center>

$$
\begin{align*}
= &\Pr(G = 10, H = 1 \mid \Omega) \\[0.6em]
= &\frac{\#(G = 10, H = 1, \Omega)}{\#\text{ Total }(\Omega)\text{ ✅}}
\end{align*}
$$

:::
::: {.column width="33%"}

<center>
[$\Pr(G = 10)$]{.cb2a-bg}
</center>

$$
\begin{align*}
= &\Pr(G = 10 \mid \Omega) \\[0.6em]
= &\frac{\#(G = 10, \Omega)}{\#\text{ Total }(\Omega)\text{ ✅}}
\end{align*}
$$

:::
::: {.column width="33%"}

<center>
[$\Pr(G = 10 \mid H = 1)$]{.cb3a-bg}
</center>

$$
\begin{align*}
= &\frac{\Pr(G = 10, H = 1)}{\Pr(H = 1)} \\[0.6em]
= &\frac{\#(G = 10, H = 1)}{\#(H = 1)\text{ 😳}}
\end{align*}
$$

:::
::::


## Conditional Distributions from Columns {.crunch-title .fix-tex-headers .inline-90 .text-90}

Let's extract just the $H = 1$ column:

:::: {layout="[2,1,2]" layout-valign="center"}

```{=html}
<table>
  <thead>
    <tr>
      <th></th>
      <th><span data-qmd="$H = 1$"></span></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><span data-qmd="$G = 10$"></span></td>
      <td class='cb3a-bg'>5</td>
    </tr>
    <tr>
      <td><span data-qmd="$G = 11$"></span></td>
      <td class='cb3a-bg'>4</td>
    </tr>
    <tr>
      <td><span data-qmd="$G = 12$"></span></td>
      <td class='cb3a-bg'>1</td>
    </tr>
    <tr>
      <td><span data-qmd="**Total**"></span></td>
      <td class='cbga-bg'>10</td>
    </tr>
  </tbody>
</table>
```

::: {#conditional-arrow-col}

<center>
<i class='bi bi-arrow-right'></i>
</center>

:::

```{=html}
<table>
  <thead>
    <tr>
      <th></th>
      <th><span data-qmd="$H = 1$"></span></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><span data-qmd="$G = 10$"></span></td>
      <td class='cb3a-bg'><span data-qmd="$\frac{5}{10}$"></span></td>
    </tr>
    <tr>
      <td><span data-qmd="$G = 11$"></span></td>
      <td class='cb3a-bg'><span data-qmd="$\frac{4}{10}$"></span></td>
    </tr>
    <tr>
      <td><span data-qmd="$G = 12$"></span></td>
      <td class='cb3a-bg'><span data-qmd="$\frac{1}{10}$"></span></td>
    </tr>
    <tr>
      <td><span data-qmd="**Total**"></span></td>
      <td class='cbga-bg'><span data-qmd="$\frac{10}{10}$"></span></td>
    </tr>
  </tbody>
</table>
```

:::


* Before, [**10**]{.cb2a-bg} was a particular **[marginal frequency]{.cb2a-bg} of interest**; now [**10**]{.cbga-bg} is just a [**total**]{.cbga-bg} that we use to **renormalize**

## Conditional Distributions from Rows {.fix-tex-headers .text-90}

Let's extract just the $G = 10$ row:

::: {layout="[[2],[1],[2]]" layout-valign="center" layout-align="center"}

```{=html}
<table style="width: 100% !important;">
  <thead>
    <tr>
      <th></th>
      <th align="center"><span data-qmd="$H = 0$"></span></th>
      <th align="center"><span data-qmd="$H = 1$"></span></th>
      <th align="center">Total</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="center"><span data-qmd="$G = 10$"></span></td>
      <td class='cb3a-bg'>5</td>
      <td class='cb3a-bg'>10</td>
      <td class='cbga-bg'>15</td>
    </tr>
  </tbody>
</table>
```

::: {#arrow-col}

<center>
<i class='bi bi-arrow-down'></i>
</center>

:::
```{=html}
<table style="width: 100% !important;">
  <thead>
    <tr>
      <th></th>
      <th align="center"><span data-qmd="$H = 0$"></span></th>
      <th align="center"><span data-qmd="$H = 1$"></span></th>
      <th align="center">Total</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="center"><span data-qmd="$G = 10$"></span></td>
      <td class='cb3a-bg'><span data-qmd="$\frac{5}{15}$"></span></td>
      <td class='cb3a-bg'><span data-qmd="$\frac{10}{15}$"></span></td>
      <td class='cbga-bg'><span data-qmd="$\frac{15}{15}$"></span></td>
    </tr>
  </tbody>
</table>
```

:::


* Before, [**15**]{.cb2a-bg} was a particular **[marginal frequency]{.cb2a-bg} of interest**; now [**15**]{.cbga-bg} is just a [**total**]{.cbga-bg} that we use to **renormalize**

## Discrete World Summary {.smaller .inline-85 .crunch-title}

We now have the **link** between three types of distributions derived from our table:

:::: {layout="[60,40]" layout-valign="top"}
::: {#discrete-summary-overview .text-80}

| Distribution Type | How Many? | Example Value |
|:-|:-:|:- |
| [**Joint Distribution**]{.cb1a-bg} | 1 | $\Pr(G = 11, H = 1) = \frac{4}{33}$ |
| [**Marginal Distributions**]{.cb2a-bg} | 2 | $\Pr(H = 1) = \frac{10}{33}$ |
| [**Conditional Distributions**]{.cb3a-bg} | 6 | $\Pr(G = 10 \mid H = 1) = \frac{5}{10}$ |

: {tbl-colwidths="[25,20,55]"}

:::
::: {#discrete-summary-tables}

```{=html}
<table style="margin-bottom: 8px !important;">
  <thead>
    <tr>
      <th></th>
      <th class='small-tex-th'><span data-qmd="$H = 0$"></span></th>
      <th class='small-tex-th'><span data-qmd="$H = 1$"></span></th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <td class='small-tex-td'><span data-qmd="$G = 10$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{10}{33}$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{5}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{15}{33}$"></span></td>
  </tr>
  <tr>
    <td class='small-tex-td'><span data-qmd="$G = 11$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{6}{33}$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{4}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{10}{33}$"></span></td>
  </tr>
  <tr>
    <td class='small-tex-td'><span data-qmd="$G = 12$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{7}{33}$"></span></td>
    <td class='cb1a-bg'><span data-qmd="$\frac{1}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{8}{33}$"></span></td>
  </tr>
  <tr>
    <td><span data-qmd="**Total**"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{23}{33}$"></span></td>
    <td class='cb2a-bg'><span data-qmd="$\frac{10}{33}$"></span></td>
    <td class='cbga-bg'><span data-qmd="$\frac{33}{33}$"></span></td>
  </tr>
  </tbody>
</table>
```

```{=html}
<table style="width: 100% !important;">
  <thead>
    <tr>
      <th></th>
      <th style="text-align: center; border-right: 2px solid black;"><span data-qmd="$H = 0$"></span></th>
      <th style="text-align: center;"><span data-qmd="$H = 1$"></span></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><span data-qmd="$G = 10$"></span></td>
      <td class='cb3a-bg' style="border-right: 2px solid black;"><span data-qmd="$\frac{10}{23}$"></span></td>
      <td class='cb3a-bg'><span data-qmd="$\frac{5}{10}$"></span></td>
    </tr>
    <tr>
      <td><span data-qmd="$G = 11$"></span></td>
      <td class='cb3a-bg' style="border-right: 2px solid black;"><span data-qmd="$\frac{6}{23}$"></span></td>
      <td class='cb3a-bg'><span data-qmd="$\frac{4}{10}$"></span></td>
    </tr>
    <tr>
      <td><span data-qmd="$G = 12$"></span></td>
      <td class='cb3a-bg' style="border-right: 2px solid black;"><span data-qmd="$\frac{7}{23}$"></span></td>
      <td class='cb3a-bg'><span data-qmd="$\frac{1}{10}$"></span></td>
    </tr>
    <tr>
      <td><span data-qmd="**Total**"></span></td>
      <td class='cbga-bg' style="border-right: 2px solid black;"><span data-qmd="$\frac{23}{23}$"></span></td>
      <td class='cbga-bg'><span data-qmd="$\frac{10}{10}$"></span></td>
    </tr>
  </tbody>
</table>
```

:::
::::

## Working Backwards {.crunch-title .inline-90 .math-90 .text-95 .crunch-math .quarto-layout-cell-no-margin}

* Here we **started** from the [joint distribution]{.cb1a-bg} and **derived** [marginal]{.cb2a-bg} and [conditional]{.cb3a-bg} distributions
* Same intuition, plus math, lets us go in **opposite direction**: **given** [marginal]{.cb2a-bg} and [conditional]{.cb3a-bg} distributions, can **derive** [joint distribution]{.cb1a-bg}, since *(conditional prob defn)*:

::: {layout="[3,1,5]" layout-valign="center"}

```{=html}
<table style="border-bottom: 0px solid black !important; border-spacing: 2px !important;">
<tbody>
  <tr style="border-bottom: 0px solid black;">
    <td rowspan="2" style="vertical-align: middle; text-align: center; border-bottom: 0px solid black !important; padding-left: 2px; padding-right: 2px;" class='cb3a-bg'><span data-qmd="$\Pr(A \mid B)$"></span></td>
    <td rowspan="2" style="vertical-align: middle; text-align: center; border-bottom: 0px solid black !important; padding-left: 4px; padding-right: 4px;"><span data-qmd="$=$"></span></td>
    <td class='cb1a-bg' style="border-bottom: 3px solid black;"><span data-qmd="$\Pr(A, B)$"></span></td>
  </tr>
  <tr>
    <td class='cb2a-bg'><span data-qmd="$\Pr(B)$"></span></td>
  </tr>
</tbody>
</table>
```

$$
\iff
$$

```{=html}
<table>
<tbody>
  <tr>
    <td style="width: 0.1%; white-space: nowrap; padding: 0px !important; text-align: center !important;" class='cb1a-bg'><span data-qmd="$\Pr(A,B)$"></span></td>
    <td align="center" style="text-align: center !important; width: 0.1% !important; white-space: nowrap !important; padding: 2px !important;"><span data-qmd="$=$"></span></td>
    <td style="width: 0.1% !important; white-space: nowrap !important; padding: 0px !important;" class='cb3a-bg'><span data-qmd="$\Pr(A \mid B)$"></span></td>
    <td align="center" style="width: 0.1% !important; white-space: nowrap !important; padding: 2px !important; text-align: center !important;"><span data-qmd="$\cdot$"></span></td>
    <td style="width: 0.1% !important; white-space: nowrap !important; padding: 0px !important;" class='cb2a-bg'><span data-qmd="$\Pr(B)$"></span></td>
  </tr>
</tbody>
</table>
```

:::

::: {.notes}

from which we can see that if we know the **conditional distribution** $\Pr(B \mid A)$ and the **marginal distribution** $\Pr(A)$, we can combine these (via multiplication) to obtain the **joint distribution** $\Pr(B,A)$.

:::
