
:::: {.columns}
::: {.column width="50%"}

* **Discrete** = "Easy mode": Based (intuitively) on **sets**
* $\Pr(A)$: Four equally-likely marbles $\{A, B, C, D\}$ in box, what is probability I pull out $A$?

```{r, dev.args=list(bg="transparent")}
#| fig-height: 5.5
library(tibble)
library(ggplot2)
disc_df <- tribble(
  ~x, ~y, ~label,
  0, 0, "A",
  0, 1, "B",
  1, 0, "C",
  1, 1, "D"
)
disc_df |> ggplot(aes(x=x, y=y, label=label)) +
  geom_point(size=g_pointsize) +
  geom_text(
    size=g_textsize,
    hjust=1.5,
    vjust=-0.5
  ) +
  xlim(-0.5,1.5) + ylim(-0.5,1.5) +
  coord_fixed() +
  dsan_theme("quarter") +
  theme(
    panel.background = element_rect(
      fill = "transparent",
      color = NA_character_
    ),
    plot.background = element_rect(
      fill = "transparent",
      color = NA_character_
    ),
    rect = element_rect(fill = "transparent"),
  ) +
  labs(title="Discrete Probability Space")
```

$$
\Pr(A) = \underset{\mathclap{\small \text{Probability }\textbf{mass}}}{\boxed{\frac{|\{A\}|}{|\Omega|}}} = \frac{1}{|\{A,B,C,D\}|} = \frac{1}{4}
$$

:::
::: {.column width="50%"}

* **Continuous** = "Hard mode": Based (intuitively) on **areas**
* $\Pr(A)$: Throw dart at random point in square, what is probability I hit $\require{enclose}\enclose{circle}{\textsf{A}}$?

```{r, dev.args=list(bg="transparent")}
#| fig-height: 6
library(ggforce)
disc_df |> ggplot(aes(x=x, y=y, label=label)) +
  xlim(-0.5,1.5) + ylim(-0.5,1.5) +
  geom_rect(aes(xmin = -0.5, xmax = 1.5, ymin = -0.5, ymax = 1.5), fill=cbPalette[1], color="black", alpha=0.3) +
  geom_circle(aes(x0=x, y0=y, r=0.25), fill=cbPalette[2]) +
  coord_fixed() +
  dsan_theme("quarter") +
  geom_text(
    size=g_textsize,
    #hjust=1.75,
    #vjust=-0.75
  ) +
  geom_text(
    data=data.frame(label="Ω"),
    aes(x=-0.4,y=1.39),
    parse=TRUE,
    size=10
  ) +
  theme(
    panel.background = element_rect(
      fill = "transparent",
      color = NA_character_
    ),
    plot.background = element_rect(
      fill = "transparent",
      color = NA_character_
    ),
    rect = element_rect(fill = "transparent"),
  ) +
  labs(title="Continuous Probability Space")
```

$$
\Pr(A) = \underset{\mathclap{\small \text{Probability }\textbf{density}}}{\boxed{\frac{\text{Area}(\{A\})}{\text{Area}(\Omega)}}} = \frac{\pi r^2}{s^2} = \frac{\pi \left(\frac{1}{4}\right)^2}{4} = \frac{\pi}{64}
$$

:::
::::